const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    FETCH_GENRE_START: 'FETCH_GENRE_START',
    FETCH_GENRE_SUCCESS: 'FETCH_GENRE_SUCCESS',
    FETCH_GENRE_FAILED: 'FETCH_GENRE_FAILED',


    FETCH_PROVINCE_SUCCESS: 'FETCH_PROVINCE_SUCCESS',
    FETCH_PROVINCE_FAILED: 'FETCH_PROVINCE_FAILED',

    FETCH_THEATER_SUCCESS: 'FETCH_THEATER_SUCCESS',
    FETCH_THEATER_FAILED: 'FETCH_THEATER_FAILED',

    FETCH_CINEMA_ROOM_SUCCESS: 'FETCH_CINEMA_ROOM_SUCCESS',
    FETCH_CINEMA_ROOM_FAILED: 'FETCH_CINEMA_ROOM_FAILED',

    CREATE_MOVIE_SUCCESS: 'SAVE_MOVIE_SUCCESS',
    CREATE_MOVIE_FAILED: 'SAVE_MOVIE_FAILED',

    FETCH_ALL_MOVIE_SUCCESS: 'FETCH_ALL_MOVIE_SUCCESS',
    FETCH_ALL_MOVIE_FAILED: 'FETCH_ALL_MOVIE_SUCCESS',

    // FETCH_MOVIE_SUCCESS: 'FETCH_MOVIE_SUCCESS',
    // FETCH_MOVIE_FAILED: 'FETCH_MOVIE_FAILED',

    FETCH_NOW_SHOWING_SUCCESS: 'FETCH_NOW_SHOWING_SUCCESS',
    FETCH_NOW_SHOWING_FAILED: 'FETCH_NOW_SHOWING_SUCCESS',

})

export default actionTypes;