const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    FETCH_GENRE_START: 'FETCH_GENRE_START',
    FETCH_GENRE_SUCCESS: 'FETCH_GENRE_SUCCESS',
    FETCH_GENRE_FAILED: 'FETCH_GENRE_FAILED',


    FETCH_PROVINCE_SUCCESS: 'FETCH_PROVINCE_SUCCESS',
    FETCH_PROVINCE_FAILED: 'FETCH_PROVINCE_FAILED',

    FETCH_THEATER_SUCCESS: 'FETCH_THEATER_SUCCESS',
    FETCH_THEATER_FAILED: 'FETCH_THEATER_FAILED',

    FETCH_FOOD_SUCCESS: 'FETCH_FOOD_SUCCESS',
    FETCH_FOOD_FAILED: 'FETCH_FOOD_FAILED',

    FETCH_CINEMA_ROOM_SUCCESS: 'FETCH_CINEMA_ROOM_SUCCESS',
    FETCH_CINEMA_ROOM_FAILED: 'FETCH_CINEMA_ROOM_FAILED',

    CREATE_MOVIE_SUCCESS: 'SAVE_MOVIE_SUCCESS',
    CREATE_MOVIE_FAILED: 'SAVE_MOVIE_FAILED',

    CREATE_FOOD_SUCCESS: 'SAVE_FOOD_SUCCESS',
    CREATE_FOOD_FAILED: 'SAVE_FOOD_FAILED',

    CREATE_EVENT_SUCCESS: 'SAVE_EVENT_SUCCESS',
    CREATE_EVENT_FAILED: 'SAVE_EVENT_FAILED',

    CREATE_TICKET_SUCCESS: 'SAVE_TICKET_SUCCESS',
    CREATE_TICKET_FAILED: 'SAVE_TICKET_FAILED',

    CREATE_BILL_FOOD_SUCCESS: 'SAVE_BILL_FOOD_SUCCESS',
    CREATE_BILL_FOOD_FAILED: 'SAVE_BILL_FOOD_FAILED',

    CREATE_DETAIL_TICKET_SUCCESS: 'SAVE_DETAIL_TICKET_SUCCESS',
    CREATE_DETAIL_TICKET_FAILED: 'SAVE_DETAIL_TICKET_FAILED',

    FETCH_ALL_MOVIE_SUCCESS: 'FETCH_ALL_MOVIE_SUCCESS',
    FETCH_ALL_MOVIE_FAILED: 'FETCH_ALL_MOVIE_FAILED',

    // FETCH_MOVIE_SUCCESS: 'FETCH_MOVIE_SUCCESS',
    // FETCH_MOVIE_FAILED: 'FETCH_MOVIE_FAILED',

    FETCH_NOW_SHOWING_SUCCESS: 'FETCH_NOW_SHOWING_SUCCESS',
    FETCH_NOW_SHOWING_FAILED: 'FETCH_NOW_SHOWING_FAILED',

    FETCH_EVENT_SUCCESS: 'FETCH_EVENT_SUCCESS',
    FETCH_EVENT_FAILED: 'FETCH_EVENT_FAILED',

    FETCH_SHOWTIME_SUCCESS: 'FETCH_SHOWTIME_SUCCESS',
    FETCH_SHOWTIME_FAILED: 'FETCH_SHOWTIME_FAILED',

    FETCH_MOVIE_FORMAT_SUCCESS: 'FETCH_MOVIE_FORMAT_SUCCESS',
    FETCH_MOVIE_FORMAT_FAILED: 'FETCH_MOVIE_FORMAT_FAILED',

    FETCH_MOVIE_FORMAT_BY_ID_SUCCESS: 'FETCH_MOVIE_FORMAT_BY_ID_SUCCESS',
    FETCH_MOVIE_FORMAT_BY_ID_FAILED: 'FETCH_MOVIE_FORMAT_BY_ID_FAILED',


    FETCH_THEATER_BY_ID_SUCCESS: 'FETCH_THEATER_BY_ID_SUCCESS',
    FETCH_THEATER_BY_ID_FAILED: 'FETCH_THEATER_BY_ID_FAILED',
})

export default actionTypes;